local settings = require("Input.Settings")

local Lua51Enums = {
	[0]  = {Mnemonic = "MOVE",      Type = "iABC",  PseudoCode = "R(A) := R(B)"},
	[1]  = {Mnemonic = "LOADK",     Type = "iABx",  PseudoCode = "R(A) := Kst(Bx)"},
	[2]  = {Mnemonic = "LOADBOOL",  Type = "iABC",  PseudoCode = "R(A) := (Bool)B; if (C) pc++"},
	[3]  = {Mnemonic = "LOADNIL",   Type = "iABC",  PseudoCode = "R(A), R(A+1), ..., R(A+B-1) := nil"},
	[4]  = {Mnemonic = "GETUPVAL",  Type = "iABC",  PseudoCode = "R(A) := UpValue[B]"},
	[5]  = {Mnemonic = "GETGLOBAL", Type = "iABx",  PseudoCode = "R(A) := Gbl[Kst(Bx)]"},
	[6]  = {Mnemonic = "GETTABLE",  Type = "iABC",  PseudoCode = "R(A) := R(B)[RK(C)]"},
	[7]  = {Mnemonic = "SETGLOBAL", Type = "iABx",  PseudoCode = "Gbl[Kst(Bx)] := R(A)"},
	[8]  = {Mnemonic = "SETUPVAL",  Type = "iABC",  PseudoCode = "UpValue[B] := R(A)"},
	[9]  = {Mnemonic = "SETTABLE",  Type = "iABC",  PseudoCode = "R(A)[RK(B)] := RK(C)"},
	[10] = {Mnemonic = "NEWTABLE",  Type = "iABC",  PseudoCode = "R(A) := {}; size = B, C"},
	[11] = {Mnemonic = "SELF",      Type = "iABC",  PseudoCode = "R(A+1) := R(B); R(A) := R(B)[RK(C)]"},
	[12] = {Mnemonic = "ADD",       Type = "iABC",  PseudoCode = "R(A) := RK(B) + RK(C)"},
	[13] = {Mnemonic = "SUB",       Type = "iABC",  PseudoCode = "R(A) := RK(B) - RK(C)"},
	[14] = {Mnemonic = "MUL",       Type = "iABC",  PseudoCode = "R(A) := RK(B) * RK(C)"},
	[15] = {Mnemonic = "DIV",       Type = "iABC",  PseudoCode = "R(A) := RK(B) / RK(C)"},
	[16] = {Mnemonic = "MOD",       Type = "iABC",  PseudoCode = "R(A) := RK(B) % RK(C)"},
	[17] = {Mnemonic = "POW",       Type = "iABC",  PseudoCode = "R(A) := RK(B) ^ RK(C)"},
	[18] = {Mnemonic = "UNM",       Type = "iABC",  PseudoCode = "R(A) := -R(B)"},
	[19] = {Mnemonic = "NOT",       Type = "iABC",  PseudoCode = "R(A) := not R(B)"},
	[20] = {Mnemonic = "LEN",       Type = "iABC",  PseudoCode = "R(A) := length of R(B)"},
	[21] = {Mnemonic = "CONCAT",    Type = "iABC",  PseudoCode = "R(A) := R(B) .. ... .. R(C)"},
	[22] = {Mnemonic = "JMP",       Type = "iAsBx", PseudoCode = "pc += sBx"},
	[23] = {Mnemonic = "EQ",        Type = "iABC",  PseudoCode = "if ((RK(B) == RK(C)) ~= A) then pc++"},
	[24] = {Mnemonic = "LT",        Type = "iABC",  PseudoCode = "if ((RK(B) < RK(C)) ~= A) then pc++"},
	[25] = {Mnemonic = "LE",        Type = "iABC",  PseudoCode = "if ((RK(B) <= RK(C)) ~= A) then pc++"},
	[26] = {Mnemonic = "TEST",      Type = "iABC",  PseudoCode = "if not (R(A) <=> C) then pc++"},
	[27] = {Mnemonic = "TESTSET",   Type = "iABC",  PseudoCode = "if (R(B) <=> C) then R(A) := R(B) else pc++"},
	[28] = {Mnemonic = "CALL",      Type = "iABC",  PseudoCode = "R(A), ..., R(A+C-2) := R(A)(R(A+1), ..., R(A+B-1))"},
	[29] = {Mnemonic = "TAILCALL",  Type = "iABC",  PseudoCode = "return R(A)(R(A+1), ..., R(A+B-1))"},
	[30] = {Mnemonic = "RETURN",    Type = "iABC",  PseudoCode = "return R(A), ..., R(A+B-2)"},
	[31] = {Mnemonic = "FORLOOP",   Type = "iAsBx", PseudoCode = "R(A) += R(A+2); if R(A) <= R(A+1) then { pc += sBx; R(A+3) = R(A) }"},
	[32] = {Mnemonic = "FORPREP",   Type = "iAsBx", PseudoCode = "R(A) -= R(A+2); pc += sBx"},
	[33] = {Mnemonic = "TFORLOOP",  Type = "iABC",  PseudoCode = "R(A+3), ..., R(A+2+C) := R(A)(R(A+1), R(A+2)); if R(A+3) ~= nil then R(A+2) = R(A+3) else pc++"},
	[34] = {Mnemonic = "SETLIST",   Type = "iABC",  PseudoCode = "R(A)[(C-1)*FPF+i] := R(A+i), 1 <= i <= B"},
	[35] = {Mnemonic = "CLOSE",     Type = "iABC",  PseudoCode = "close all variables in the stack up to (>=) R(A)"},
	[36] = {Mnemonic = "CLOSURE",   Type = "iABx",  PseudoCode = "R(A) := closure(KPROTO[Bx], R(A), ..., R(A+n))"},
	[37] = {Mnemonic = "VARARG",    Type = "iABC",  PseudoCode = "R(A), R(A+1), ..., R(A+B-1) := vararg"},
	[38] = {Mnemonic = "INVALID",   Type = "",       PseudoCode = "Invalid opcode or undefined behavior"},
}

-- Luau opcode set (80+ opcodes, AD/E encoding)
-- These use Luau's bytecode format: ABC, AD, or E encoding
local LuauEnums = {
	[0]  = {Mnemonic = "NOP",           Type = "iABC",  PseudoCode = "no-op"},
	[1]  = {Mnemonic = "BREAK",         Type = "iABC",  PseudoCode = "debugger break"},
	[2]  = {Mnemonic = "LOADNIL",       Type = "iAD",   PseudoCode = "R(A) := nil"},
	[3]  = {Mnemonic = "LOADB",         Type = "iABC",  PseudoCode = "R(A) := (bool)B; if C then pc++"},
	[4]  = {Mnemonic = "LOADN",         Type = "iAD",   PseudoCode = "R(A) := D (integer literal)"},
	[5]  = {Mnemonic = "LOADK",         Type = "iAD",   PseudoCode = "R(A) := K(D)"},
	[6]  = {Mnemonic = "MOVE",          Type = "iABC",  PseudoCode = "R(A) := R(B)"},
	[7]  = {Mnemonic = "GETUPVAL",      Type = "iABC",  PseudoCode = "R(A) := UpValue[B]"},
	[8]  = {Mnemonic = "SETUPVAL",      Type = "iABC",  PseudoCode = "UpValue[B] := R(A)"},
	[9]  = {Mnemonic = "CLOSEUPVALS",   Type = "iABC",  PseudoCode = "close upvalues >= R(A)"},
	[10] = {Mnemonic = "GETIMPORT",     Type = "iAD",   PseudoCode = "R(A) := Import[D] (AUX = import path)"},
	[11] = {Mnemonic = "GETTABLE",      Type = "iABC",  PseudoCode = "R(A) := R(B)[R(C)]"},
	[12] = {Mnemonic = "SETTABLE",      Type = "iABC",  PseudoCode = "R(A)[R(B)] := R(C)"},
	[13] = {Mnemonic = "GETTABLEKS",    Type = "iABC",  PseudoCode = "R(A) := R(B)[K(AUX)] (string key)"},
	[14] = {Mnemonic = "SETTABLEKS",    Type = "iABC",  PseudoCode = "R(A)[K(AUX)] := R(B) (string key)"},
	[15] = {Mnemonic = "GETTABLEN",     Type = "iABC",  PseudoCode = "R(A) := R(B)[C] (integer index)"},
	[16] = {Mnemonic = "SETTABLEN",     Type = "iABC",  PseudoCode = "R(A)[C] := R(B) (integer index)"},
	[17] = {Mnemonic = "NEWCLOSURE",    Type = "iAD",   PseudoCode = "R(A) := closure(Proto[D])"},
	[18] = {Mnemonic = "NAMECALL",      Type = "iABC",  PseudoCode = "R(A+1) := R(B); R(A) := R(B)[K(AUX)]"},
	[19] = {Mnemonic = "CALL",          Type = "iABC",  PseudoCode = "R(A), ..., R(A+C-2) := R(A)(R(A+1), ..., R(A+B-1))"},
	[20] = {Mnemonic = "RETURN",        Type = "iABC",  PseudoCode = "return R(A), ..., R(A+B-2)"},
	[21] = {Mnemonic = "JUMP",          Type = "iE",    PseudoCode = "pc += E"},
	[22] = {Mnemonic = "JUMPBACK",      Type = "iE",    PseudoCode = "pc += E (backward jump for loops)"},
	[23] = {Mnemonic = "JUMPIF",        Type = "iAD",   PseudoCode = "if R(A) then pc += D"},
	[24] = {Mnemonic = "JUMPIFNOT",     Type = "iAD",   PseudoCode = "if not R(A) then pc += D"},
	[25] = {Mnemonic = "JUMPIFEQ",      Type = "iAD",   PseudoCode = "if R(A) == R(AUX) then pc += D"},
	[26] = {Mnemonic = "JUMPIFLE",      Type = "iAD",   PseudoCode = "if R(A) <= R(AUX) then pc += D"},
	[27] = {Mnemonic = "JUMPIFLT",      Type = "iAD",   PseudoCode = "if R(A) < R(AUX) then pc += D"},
	[28] = {Mnemonic = "JUMPIFNOTEQ",   Type = "iAD",   PseudoCode = "if R(A) ~= R(AUX) then pc += D"},
	[29] = {Mnemonic = "JUMPIFNOTLE",   Type = "iAD",   PseudoCode = "if not (R(A) <= R(AUX)) then pc += D"},
	[30] = {Mnemonic = "JUMPIFNOTLT",   Type = "iAD",   PseudoCode = "if not (R(A) < R(AUX)) then pc += D"},
	[31] = {Mnemonic = "ADD",           Type = "iABC",  PseudoCode = "R(A) := R(B) + R(C)"},
	[32] = {Mnemonic = "SUB",           Type = "iABC",  PseudoCode = "R(A) := R(B) - R(C)"},
	[33] = {Mnemonic = "MUL",           Type = "iABC",  PseudoCode = "R(A) := R(B) * R(C)"},
	[34] = {Mnemonic = "DIV",           Type = "iABC",  PseudoCode = "R(A) := R(B) / R(C)"},
	[35] = {Mnemonic = "MOD",           Type = "iABC",  PseudoCode = "R(A) := R(B) % R(C)"},
	[36] = {Mnemonic = "POW",           Type = "iABC",  PseudoCode = "R(A) := R(B) ^ R(C)"},
	[37] = {Mnemonic = "ADDK",          Type = "iABC",  PseudoCode = "R(A) := R(B) + K(C)"},
	[38] = {Mnemonic = "SUBK",          Type = "iABC",  PseudoCode = "R(A) := R(B) - K(C)"},
	[39] = {Mnemonic = "MULK",          Type = "iABC",  PseudoCode = "R(A) := R(B) * K(C)"},
	[40] = {Mnemonic = "DIVK",          Type = "iABC",  PseudoCode = "R(A) := R(B) / K(C)"},
	[41] = {Mnemonic = "MODK",          Type = "iABC",  PseudoCode = "R(A) := R(B) % K(C)"},
	[42] = {Mnemonic = "POWK",          Type = "iABC",  PseudoCode = "R(A) := R(B) ^ K(C)"},
	[43] = {Mnemonic = "AND",           Type = "iABC",  PseudoCode = "R(A) := R(B) and R(C)"},
	[44] = {Mnemonic = "OR",            Type = "iABC",  PseudoCode = "R(A) := R(B) or R(C)"},
	[45] = {Mnemonic = "ANDK",          Type = "iABC",  PseudoCode = "R(A) := R(B) and K(C)"},
	[46] = {Mnemonic = "ORK",           Type = "iABC",  PseudoCode = "R(A) := R(B) or K(C)"},
	[47] = {Mnemonic = "CONCAT",        Type = "iABC",  PseudoCode = "R(A) := R(B) .. ... .. R(C)"},
	[48] = {Mnemonic = "NOT",           Type = "iABC",  PseudoCode = "R(A) := not R(B)"},
	[49] = {Mnemonic = "MINUS",         Type = "iABC",  PseudoCode = "R(A) := -R(B)"},
	[50] = {Mnemonic = "LENGTH",        Type = "iABC",  PseudoCode = "R(A) := #R(B)"},
	[51] = {Mnemonic = "NEWTABLE",      Type = "iABC",  PseudoCode = "R(A) := {} (B=array hint, AUX=hash hint)"},
	[52] = {Mnemonic = "DUPTABLE",      Type = "iAD",   PseudoCode = "R(A) := duplicate(K(D)) (template table)"},
	[53] = {Mnemonic = "SETLIST",       Type = "iABC",  PseudoCode = "R(A)[B..B+C-1] := R(A+1)..R(A+C)"},
	[54] = {Mnemonic = "FORNPREP",      Type = "iAD",   PseudoCode = "prepare numeric for loop; jump D if invalid"},
	[55] = {Mnemonic = "FORNLOOP",      Type = "iAD",   PseudoCode = "numeric for loop step; jump D if not done"},
	[56] = {Mnemonic = "FORGPREP",      Type = "iAD",   PseudoCode = "prepare generic for loop, jump D"},
	[57] = {Mnemonic = "FORGLOOP",      Type = "iAD",   PseudoCode = "generic for loop step; AUX=iter count"},
	[58] = {Mnemonic = "FORGPREP_INEXT",Type = "iAD",   PseudoCode = "prepare ipairs-style generic for"},
	[59] = {Mnemonic = "FORGLOOP_INEXT",Type = "iAD",   PseudoCode = "ipairs-style generic for loop step"},
	[60] = {Mnemonic = "FORGPREP_NEXT", Type = "iAD",   PseudoCode = "prepare pairs-style generic for"},
	[61] = {Mnemonic = "FORGLOOP_NEXT", Type = "iAD",   PseudoCode = "pairs-style generic for loop step"},
	[62] = {Mnemonic = "GETVARARGS",    Type = "iABC",  PseudoCode = "R(A) ... R(A+B-1) := vararg"},
	[63] = {Mnemonic = "DUPCLOSURE",    Type = "iAD",   PseudoCode = "R(A) := closure(Proto[D]) (reuse existing)"},
	[64] = {Mnemonic = "PREPVARARGS",   Type = "iABC",  PseudoCode = "prepare varargs for function (A=numparams)"},
	[65] = {Mnemonic = "LOADKX",        Type = "iAD",   PseudoCode = "R(A) := K(AUX) (extended constant index)"},
	[66] = {Mnemonic = "JUMPX",         Type = "iE",    PseudoCode = "pc += E (extended jump)"},
	[67] = {Mnemonic = "FASTCALL",      Type = "iABC",  PseudoCode = "fast call to builtin function A"},
	[68] = {Mnemonic = "COVERAGE",      Type = "iE",    PseudoCode = "update coverage counter (E = hit count)"},
	[69] = {Mnemonic = "CAPTURE",       Type = "iABC",  PseudoCode = "capture upvalue: A=type, B=source"},
	[70] = {Mnemonic = "SUBRK",         Type = "iABC",  PseudoCode = "R(A) := K(B) - R(C)"},
	[71] = {Mnemonic = "DIVRK",         Type = "iABC",  PseudoCode = "R(A) := K(B) / R(C)"},
	[72] = {Mnemonic = "FASTCALL1",     Type = "iABC",  PseudoCode = "fast call builtin A with 1 arg R(B)"},
	[73] = {Mnemonic = "FASTCALL2",     Type = "iABC",  PseudoCode = "fast call builtin A with 2 args R(B), R(AUX)"},
	[74] = {Mnemonic = "FASTCALL2K",    Type = "iABC",  PseudoCode = "fast call builtin A with args R(B), K(AUX)"},
	[75] = {Mnemonic = "FORGPREP",      Type = "iAD",   PseudoCode = "generic for prepare (version 3+)"},
	[76] = {Mnemonic = "JUMPXEQKNIL",   Type = "iAD",   PseudoCode = "jump if R(A) == nil (AUX has NOT flag)"},
	[77] = {Mnemonic = "JUMPXEQKB",     Type = "iAD",   PseudoCode = "jump if R(A) == bool K (AUX has value+NOT)"},
	[78] = {Mnemonic = "JUMPXEQKN",     Type = "iAD",   PseudoCode = "jump if R(A) == number K(AUX)"},
	[79] = {Mnemonic = "JUMPXEQKS",     Type = "iAD",   PseudoCode = "jump if R(A) == string K(AUX)"},
	[80] = {Mnemonic = "IDIV",          Type = "iABC",  PseudoCode = "R(A) := floor(R(B) / R(C))"},
	[81] = {Mnemonic = "IDIVK",         Type = "iABC",  PseudoCode = "R(A) := floor(R(B) / K(C))"},
	[82] = {Mnemonic = "INVALID",       Type = "",       PseudoCode = "Invalid opcode or undefined behavior"},
}

if settings.LuauMode then
	return LuauEnums
else
	return Lua51Enums
end
